main/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
]

rumahsakit/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'rumahsakit'




urlpatterns = [
    path('rumahsakit/create_reservasi', views.form_create_reservasi_rs, name='create_form_reservasi_rs'),
    path('rumahsakit/create_rs', views.form_create_rs, name='create_form_rs'),
    path('rumahsakit/list_rs', views.list_rs, name='list_rs'),
    path('rumahsakit/update_rs/<str:row>', views.update_rs, name='update_rs'),
    path('rumahsakit/list_ruangan', views.get_ruangan, name='list_ruang'),
    path('rumahsakit/list_bed', views.get_bed, name='list_bed'),
    path('rumahsakit/list_reservasi', views.list_reservasi_rs, name='list_reservasi'),
    path('rumahsakit/update_reservasi/<str:row>/<str:row2>', views.update_reservasi_rs, name='update_reservasi'),
    path('rumahsakit/delete_reservasi/<str:row>/<str:row2>', views.delete_reservasi_rs, name='delete_reservasi'),
]

siruco/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('user_profile.urls')),
    path('', include('rumahsakit.urls')),
    path('', include('faskes.urls')),
    path('',include('pasien.urls')),
    path('',include('hotel.urls')),
    path('',include('transaksi_makanan.urls')), 
    path('', include('transaksi_rs.urls'))
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'users'

urlpatterns = [
    path('register/adminsistem', views.register_admin_sistem, name='register_admin_sistem'),
    path('register/adminsatgas', views.register_admin_satgas, name='register_admin_satgas'),
    path('register/dokter', views.register_dokter, name='register_dokter'),
    path('register/penggunapublik', views.register_pengguna_publik, name='register_pengguna_publik'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),

]

rumahsakit/models.py
from django.db import models

# Create your models here.

rumahsakit/forms.py
from django import forms
from django.db import connection

class CreateRS(forms.Form):
    def get_all_faskes():
        cursor=connection.cursor()
        cursor.execute("SET SEARCH_PATH TO SIRUCO;")
        cursor.execute("select kode,kode FROM FASKES WHERE tipe = 'Rumah Sakit';")
        list_kode_rs = cursor.fetchall()
        cursor.close()

        return list_kode_rs

    kode_rs = forms.ChoiceField(label="Kode RS", choices= get_all_faskes(), required=True)

    rujukan = forms.BooleanField(label='rujukan',  required=False)

class UpdateRS(forms.Form):

    kode_rs = forms.CharField(label="Kode_rs", required=True, disabled=True)

    rujukan = forms.BooleanField(label='rujukan', required=False)

class ReservasiRS(forms.Form):

    def get_all_NIK():
        cursor=connection.cursor()
        cursor.execute("SET SEARCH_PATH TO SIRUCO;")
        cursor.execute("select NIK,NIK FROM PASIEN;")
        list_nik = cursor.fetchall()
        cursor.close()

        return list_nik

    def get_all_kode_rs():
        cursor=connection.cursor()
        cursor.execute("SET SEARCH_PATH TO SIRUCO;")
        cursor.execute("select kode_faskes,kode_faskes FROM RUMAH_SAKIT;")
        list_kode_rs = cursor.fetchall()
        cursor.close()

        return list_kode_rs

    NIK_Pasien = forms.ChoiceField(label="NIK_Pasien", choices= get_all_NIK())

    tanggal_masuk = forms.CharField(label='Tanggal Masuk', widget=forms.DateInput(attrs={
        'class': 'form-control',
        'placeholder': 'NIK Pasien',
        'type' : 'date',
        'required': True,
        }))

    tanggal_keluar = forms.CharField(label='Tanggal Keluar', widget=forms.DateInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tanggal Keluar',
        'type' : 'date',
        'required': True,
        }))
    
    kode_rs = forms.ChoiceField(label="Kode RS", choices= get_all_kode_rs(), required=True)

    kode_ruangan = forms.CharField(label="Kode Ruangan", required = True, widget=forms.Select(choices=[]))

    kode_bed = forms.CharField(label="Kode Bed", required=True, widget=forms.Select(choices=[]))

class UpdateReservasi(forms.Form):


    NIK_Pasien = forms.CharField(label="NIK_Pasien", required=True, disabled=True)

    tanggal_masuk = forms.CharField(label='Tanggal Masuk', required=True, disabled=True)

    tanggal_keluar = forms.CharField(label='Tanggal Keluar', widget=forms.DateInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tanggal Keluar',
        'type' : 'date',
        'required': True,
        }))
    
    kode_rs = forms.CharField(label="Kode RS", required=True, disabled=True)

    kode_ruangan = forms.CharField(label="Kode Ruangan", required = True, disabled=True)

    kode_bed = forms.CharField(label="Kode Bed", required=True, disabled=True)

rumahsakit/views.py
from django.shortcuts import render, redirect
from django.db import connection
from .forms import ReservasiRS, CreateRS,UpdateRS, UpdateReservasi
from datetime import datetime, timedelta
from django.contrib import messages
# Create your views here.

def form_create_rs(request):
    with connection.cursor() as cursor:
        response = {}
        response['error'] = False
        form = CreateRS(request.POST) 
        response['form'] = form
        if request.method == 'POST':
            if form.is_valid():
                kode_rs = request.POST.get('kode_rs')
                rujukan = form.cleaned_data['rujukan']
                if rujukan == True :
                    rujukan = 1
                if rujukan == False :
                    rujukan ==  0

               
            #    Insert Into RS
                cursor.execute("INSERT INTO RUMAH_SAKIT (kode_faskes, isrujukan)"
                               "VALUES ('{}','{}');".format(kode_rs,rujukan))

                return redirect('rumahsakit:list_rs') 
    form = CreateRS()
    args = {
        'form' : response['form'],
    }
    return render(request, 'create_rs.html', args)

def update_rs(request,row):
    value = ''
    with connection.cursor() as cursor:
        cursor.execute('SET SEARCH_PATH TO SIRUCO;')
        cursor.execute('SELECT * FROM RUMAH_SAKIT WHERE kode_faskes = %s;',[row])
        data_rs = cursor.fetchone()
        responses = {}
        responses['kode_faskes'] = data_rs[0]
        print(data_rs[0])
        responses['isrujukan'] = data_rs[1]
        print(data_rs[1])
        if data_rs[1] == '1':
            print("masuk case a")
            value = True
        if data_rs[1] == '0':
            print("masuk case b")
            value = False
        initialdict = {"kode_rs" : data_rs[0], "rujukan" : value}
        print(data_rs[1])
        print(initialdict)

    response = {}
    response['error'] = False
    form = UpdateRS(request.POST or None, initial=initialdict) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            kode_rs = row
            rujukan = form.cleaned_data['rujukan']
            print(rujukan)
            if rujukan == True :
                print("case a")
                rujukan = 1
            if rujukan == False :
                rujukan =  0
                print("case b")

               
            with connection.cursor() as cursor:
            #    Insert Into RS
                cursor.execute("UPDATE RUMAH_SAKIT SET kode_faskes = '{}', isrujukan = '{}' WHERE kode_faskes = '{}';".format(kode_rs,rujukan,kode_rs))

                return redirect('rumahsakit:list_rs')

    form = UpdateRS()
    args = {
        'form' : response['form'],
    }
    return render(request, 'update_rs.html', args)

def list_rs(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute("SELECT RS.kode_faskes, RS.isrujukan FROM rumah_sakit AS RS, faskes AS F WHERE F.tipe = 'Rumah Sakit' AND RS.kode_faskes = F.kode;" )
    list_rs = cursor.fetchall()
    print(list_rs)
    print(len(list_rs))
    args = {'list_rs':list_rs}
    return render(request, 'list_rs.html', args)

def list_reservasi_rs(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute("SELECT kodepasien, tglmasuk, tglkeluar, koders, koderuangan, kodebed FROM reservasi_rs;" )
    list_reservasi = cursor.fetchall()
    print(list_reservasi)
    print(len(list_reservasi))
    args = {'list_reservasi':list_reservasi}
    return render(request, 'list_reservasi_rs.html', args)

def delete_reservasi_rs(request,row,row2):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute(f'''DELETE FROM RESERVASI_RS WHERE kodepasien = '{row}' AND tglmasuk = '{row2}';''')
    cursor.close()
    
    return redirect('rumahsakit:list_reservasi') 

def update_reservasi_rs(request,row,row2):
    # time = row2.strftime("%Y-%b-%d")
    # print(time)
    with connection.cursor() as cursor:
        cursor.execute('SET SEARCH_PATH TO SIRUCO;')
        cursor.execute(f'''SELECT * FROM RESERVASI_RS WHERE kodepasien = '{row}' AND tglmasuk = '{row2}';''')
        data_reservasi = cursor.fetchone()
        responses = {}
        responses['kodepasien'] = data_reservasi[0]
        print(data_reservasi[0])
        responses['tglmasuk'] = data_reservasi[1]
        responses['tglkeluar'] = data_reservasi[2]
        responses['koders'] = data_reservasi[3]
        responses['koderuangan'] = data_reservasi[4]
        responses['kodebed'] = data_reservasi[5]

        initialdict = {"NIK_Pasien" : data_reservasi[0], "tanggal_masuk" : data_reservasi[1], "kode_rs" : data_reservasi[3], "kode_ruangan" : data_reservasi[4], "kode_bed" : data_reservasi[5]}
        print(initialdict)

    response = {}
    response['error'] = False
    form = UpdateReservasi(request.POST or None, initial=initialdict) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            nik = form.cleaned_data['NIK_Pasien']
            tgl_masuk = form.cleaned_data['tanggal_masuk']
            tgl_keluar = form.cleaned_data['tanggal_keluar']
            kode_rs = form.cleaned_data['kode_rs']
            kode_ruangan = form.cleaned_data['kode_ruangan']
            kode_bed = form.cleaned_data['kode_bed']
            a = tgl_keluar.split('-')
            a_year = int(a[0])
            a_month = int(a[1])
            a_day = int(a[2])

            b = tgl_masuk.split('-')
            b_year = int(b[0])
            b_month = int(b[1])
            b_day = int(b[2])

            x_year = a_year - b_year
            x_month = a_month - b_month
            x_day = a_day - b_day

            time = (x_year * 365) + (x_month * 30) + (x_day)

            print(time)

            if(time>0):   
                with connection.cursor() as cursor:
                #   Insert Into RS
                    cursor.execute("UPDATE RESERVASI_RS SET kodepasien = '{}', tglmasuk = '{}', tglkeluar = '{}', koders = '{}', koderuangan = '{}', kodebed = '{}' WHERE kodepasien = '{}' AND tglmasuk = '{}';".format(nik,tgl_masuk,tgl_keluar,kode_rs,kode_ruangan,kode_bed,nik,tgl_masuk))
                    cursor.execute(f'''SELECT * FROM RESERVASI_RS WHERE kodepasien = '{nik}' AND tglmasuk = '{tgl_masuk}';''')
                    date_update = cursor.fetchone()
                    tglkeluar = date_update[2] 
                    tglmasuk = date_update[1]
                    d = tglkeluar-tglmasuk
                    tagihan = 500000 * d.days
                    print(tagihan)
                    
                    cursor.execute("SELECT * FROM TRANSAKSI_RS WHERE kodepasien = '{}' AND tglmasuk = '{}';".format(nik,tgl_masuk))
                    data_update = cursor.fetchone()
                    cursor.execute("UPDATE TRANSAKSI_RS SET idtransaksi = '{}', kodepasien = '{}', tanggalpembayaran = NULL , waktupembayaran = NULL , tglmasuk = '{}', totalbiaya = {}, statusbayar = '{}' WHERE kodepasien = '{}' AND tglmasuk = '{}';".format(data_update[0],data_update[1],data_update[4],tagihan,data_update[6], data_update[1], data_update[4]))
                    

                    return redirect('rumahsakit:list_reservasi')

               
    form = UpdateReservasi()
    args = {
        'form' : response['form'],
    }
    return render(request, 'update_reservasi.html', args)

def form_create_reservasi_rs(request):
    response = {}
    response['error'] = False
    form = ReservasiRS(request.POST or None) 
    response['form'] = form
    print("A")
    if request.method == 'POST':
        print("B")
        if form.is_valid():
            print("C")
            NIK_Pasien = form.cleaned_data['NIK_Pasien']
            print(NIK_Pasien)
            tanggal_masuk = request.POST.get('tanggal_masuk')
            tanggal_keluar = request.POST.get('tanggal_keluar')
            kode_rs = form.cleaned_data['kode_rs']
            kode_ruangan = form.cleaned_data['kode_ruangan']
            kode_bed = form.cleaned_data['kode_bed']
            print(tanggal_masuk)
            print(tanggal_keluar)
            print(kode_rs)
            print(kode_ruangan)
            print(kode_bed)
            a = tanggal_keluar.split('-')
            a_year = int(a[0])
            a_month = int(a[1])
            a_day = int(a[2])

            b = tanggal_masuk.split('-')
            b_year = int(b[0])
            b_month = int(b[1])
            b_day = int(b[2])

            x_year = a_year - b_year
            x_month = a_month - b_month
            x_day = a_day - b_day

            time = (x_year * 365) + (x_month * 30) + (x_day)

            print(time)

            if(time>0):  
                with connection.cursor() as cursor:
                #Insert into RESERVASI_RS
                    cursor.execute("INSERT INTO RESERVASI_RS VALUES ('{}','{}','{}','{}','{}','{}');".format(NIK_Pasien,tanggal_masuk, tanggal_keluar, kode_rs, kode_ruangan, kode_bed ))
                    return redirect('rumahsakit:list_reservasi')
            
    form = ReservasiRS()
    args = {
        'form' : response['form'],
    }
    return render(request, 'create_reservasi_rs.html', args)

def get_ruangan(request):
    rumah_sakit = request.GET.get('kode_rs')
    list_ruangan = []

    with connection.cursor() as cursor:
        cursor.execute("SELECT koderuangan FROM RUANGAN_RS WHERE koders = '{}' AND jmlbed > 0;".format(rumah_sakit))
        list_ruangan = cursor.fetchall()

    final = []
    for i in list_ruangan:
        val = (i[0],i[0])
        final.append(val)
    return render(request, 'list_ruangan.html', {'list_ruangan':final})

def get_bed(request):
    rumah_sakit = request.GET.get('kode_rs')
    ruangan = request.GET.get('kode_ruang')
    list_bed = []

    with connection.cursor() as cursor:

rumahsakit/templates/create_reservasi_rs.html
{% extends 'base.html' %} 
{% block content %}

<center> Database Rumah Sakit </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:create_form_rs' %}">Buat RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'rumahsakit:list_rs' %}">List RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_dokter' %}">List Jadwal Dokter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'rumahsakit:create_form_reservasi_rs' %}">Buat Reservasi RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:list_reservasi' %}">List Reservasi RS</a>
            </li>
        </ul>
    </div>
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Create Reservasi RS</center></h4></p>
     
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">NIK Pasien</label> {{ form.NIK_Pasien }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Tanggal Masuk</label> {{ form.tanggal_masuk }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Tanggal Keluar</label> {{ form.tanggal_keluar }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kode Rumah Sakit</label> {{ form.kode_rs }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kode Ruangan</label> {{ form.kode_ruangan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kode Bed</label> {{ form.kode_bed }}
          </div>
          <input class="btn btn-primary" type="submit" value="SIMPAN">
      </form>
    </div> 
    </div>
</div>

<!-- JQUERY AJAX CODE -->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script>


  $("#id_kode_rs").change(function(){
    var url = "{% url 'rumahsakit:list_ruang' %}";
    var kode_rs = $(this).val();
    console.log(kode_rs);
    
    $.ajax({
      url: url,
      data: {
        'kode_rs' : kode_rs
      },
      success: function(data) {
        console.log('test')
        console.log(data);
        console.log('test');
        $("#id_kode_ruangan").html(data);
      }
    });
  });  
</script>
  
<script>
$("#id_kode_ruangan").change(function(){
  var url = "{% url 'rumahsakit:list_bed' %}"
  var kode_ruang = $(this).val();
  var kode_rs = $("#id_kode_rs").val();
  console.log(kode_ruang)
  console.log(kode_rs)

  $.ajax({
    url : url,
    data : {
      'kode_rs' : kode_rs,
      'kode_ruang' : kode_ruang
    },
    success: function (data) {
      console.log('test2')
      console.log(data)
      console.log('test2')
      $("#id_kode_bed").html(data);
    }
  });
});
  

</script>



{% endblock %}

rumahsakit/templates/create_rs.html
{% extends 'base.html' %} 
{% block content %}

<center> Database Rumah Sakit </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'rumahsakit:create_form_rs' %}">Buat RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'rumahsakit:list_rs' %}">List RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_dokter' %}">List Jadwal Dokter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:create_form_reservasi_rs' %}">Buat Reservasi RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:list_reservasi' %}">List Reservasi RS</a>
            </li>
        </ul>
    </div>
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Create RS</center></h4></p>
     
        <form action="{% url 'rumahsakit:create_form_rs' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">Kode Faskes</label> {{ form.kode_rs }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Rujukan</label> {{ form.rujukan }}
          </div>
          <input class="btn btn-primary" type="submit" value="SIMPAN">
      </form>
    </div> 
    </div>
</div>

{% endblock %}

rumahsakit/templates/list_bed.html
<option value="">---Pilih Bed---</option>
{% for i in list_bed %}
<option value="{{ i.0 }}">{{ i.1 }}</option>
{% endfor %}

rumahsakit/templates/list_reservasi_rs.html
{% extends "base.html" %}


{% block content %}
<style>
    .tmargin{
        padding: 32px;
    }
</style>

<center> Database Rumah Sakit </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link " href="{% url 'rumahsakit:create_form_rs' %}">Buat RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:list_rs' %}">List RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_dokter' %}">List Jadwal Dokter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:create_form_reservasi_rs' %}">Buat Reservasi RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'rumahsakit:list_reservasi' %}">List Reservasi RS</a>
            </li>
        </ul>
    </div>
<br>

<h2><center>List Rumah Sakit</center></h2>
<div class="tmargin table-responsive">
    <table class="table justify-content-center">
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">No</th>
                <th scope="col">NIK Pasien</th>
                <th scope="col">Tanggal Masuk</th>
                <th scope="col">Tanggal Keluar</th>
                <th scope="col">Rumah Sakit</th>
                <th scope="col">Ruangan</th>
                <th scope="col">Bed</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_reservasi %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{li.0}}</td>
                <td>{{li.1}}</td>
                <td>{{li.2}}</td>
                <td>{{li.3}}</td>
                <td>{{li.4}}</td>
                <td>{{li.5}}</td>                
                <td> 

                  <a class="btn btn-primary btn-am bg-success update" href="{% url 'rumahsakit:update_reservasi' row=li.0 row2=li.1 %}">Update</a>
                  <a class="btn btn-primary btn-am bg-success update" href="{% url 'rumahsakit:delete_reservasi' row=li.0 row2=li.1 %}">Delete</a>
                </td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

rumahsakit/templates/list_rs.html
{% extends "base.html" %}


{% block content %}
<style>
    .tmargin{
        padding: 32px;
    }
</style>

<center> Database Rumah Sakit </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link " href="{% url 'rumahsakit:create_form_rs' %}">Buat RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'rumahsakit:list_rs' %}">List RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_dokter' %}">List Jadwal Dokter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Ruangan RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">Buat Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register_admin_satgas' %}">List Bed RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:create_form_reservasi_rs' %}">Buat Reservasi RS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rumahsakit:list_reservasi' %}">List Reservasi RS</a>
            </li>
        </ul>
    </div>
<br>

<h2><center>List Rumah Sakit</center></h2>
<div class="tmargin table-responsive">
    <table class="table justify-content-center">
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Rumah Sakit</th>
                <th scope="col">Status Rujukan</th>
                <th scope="col">Action</th>
                <!-- {% if request.session.role == "ADMIN_APOTEK" %}
                <th scope="col">Action [ADMIN]</th>
                {% endif %} -->
            </tr>
        </thead>
        <tbody>
          {% for li in list_rs %}
            <tr>
                <td>{{li.0}}</td>
                {% if li.1 == '1' %}
                <td><input disabled type="checkbox" checked></td>
                {% endif %}
                {% if li.1 == '0' %}
                <td><input disabled type="checkbox"></td>
                {% endif %}
                
                <td> 
                  <a class="btn btn-primary btn-am bg-success update" href="{% url 'rumahsakit:update_rs' row=li.0 %}">Update</a>
                </td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

rumahsakit/templates/list_ruangan.html
<option value="">---Pilih Ruangan---</option>
{% for i in list_ruangan %}
<option value="{{ i.0 }}">{{ i.1 }}</option>
{% endfor %}