hotel/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'hotel'

urlpatterns = [
    path('hotel/create_hotel', views.form_create_hotel, name='create_hotel'),
    path('hotel/list_hotel', views.list_hotel, name='list_hotel'),
    path('hotel/update_hotel/<str:row>', views.form_update_hotel, name='update_hotel'),
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
]

siruco/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('user_profile.urls')),
    path('', include('rumahsakit.urls')),
    path('', include('faskes.urls')),
    path('',include('pasien.urls')),
    path('',include('hotel.urls')),
    path('',include('transaksi_makanan.urls')), 
    path('', include('transaksi_rs.urls'))
]

transaksi_makanan/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'transaksi_makanan'

urlpatterns = [
    path('transaksi_makan/create_paket_makan', views.create_paket_makan, name='create_paket_makan'),
    path('transaksi_makan/list_paket_makan', views.list_paket_makan, name='list_paket_makan'),
    path('transaksi_makan/update_paket_makan/<str:row1>/<str:row2>', views.update_paket_makan, name='update_paket_makan'),
    path('transaksi_makan/delete_paket_makan/<str:row1>/<str:row2>', views.delete_paket_makan, name='delete_paket_makan'),
    path('transaksi_makan/create_transaksi_makan', views.create_transaksi_makan, name='create_transaksi_makan'),
    path('transaksi_makan/list_transaksi_makan', views.list_transaksi_makan, name='list_transaksi_makan'),
    path('transaksi_makan/delete_transaksi_makan/<str:row1>/<str:row2>', views.delete_transaksi_makan, name='delete_transaksi_makan'),
    path('transaksi_makan/update_transaksi_makan/<str:row1>/<str:row2>', views.update_transaksi_makan, name='update_transaksi_makan'),
    path('transaksi_makan/detail_transaksi_makan/<str:row1>/<str:row2>', views.detail_transaksi_makan, name='detail_transaksi_makan'),
    path('transaksi_makan/get_kode_hotel', views.get_kode_hotel, name='get_kode_hotel'),
]

transaksi_makanan/models.py
from django.db import models

# Create your models here.

transaksi_makanan/forms.py
from django import forms
from django.db import connection

class CreatePaketMakanan(forms.Form):
    def get_all_kode_hotel():
        cursor=connection.cursor()
        cursor.execute("SET SEARCH_PATH TO SIRUCO;")
        cursor.execute("select kode FROM HOTEL;")
        kode_response = cursor.fetchall()
        res = []
        for tup in kode_response:
            res.append((tup[0], tup[0]))
        cursor.close()

        return res


    # Kode Hotel: H01 [Dropdown, Ambil data dari tabel HOTEL]
    kode_hotel = forms.ChoiceField(label="Kode Hotel", choices= get_all_kode_hotel())

    # Kode Paket: MACEH [Isian]
    kode_paket = forms.CharField(label='Kode Paket', max_length=5, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis kode paket',
        'type' : 'text',
        'required': True,
    }))

    # Nama Paket: Mie Aceh dengan Bumbu Spesial “Minyak Babi Panggang”.
    nama_paket = forms.CharField(label='Nama Paket', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis kode paket',
        'type' : 'text',
        'required': True,
    }))
    
    # Harga: Rp70.000 [Isian]
    harga = forms.IntegerField(label='Harga',required=True,widget=forms.NumberInput,min_value=0)

class UpdatePaketMakanan(forms.Form):
    kode_hotel = forms.CharField(label='Kode Hotel', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))

    kode_paket =  forms.CharField(label='Kode Hotel', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))

    nama_paket = forms.CharField(label='Nama Paket', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis kode paket',
        'type' : 'text',
        'required': True,
    }))

    harga = forms.IntegerField(label='Harga',required=False,widget=forms.NumberInput)

class CreateTransaksiMakan(forms.Form):
    def get_data_transaksi_hotel():
        cursor=connection.cursor()
        cursor.execute("SET SEARCH_PATH TO SIRUCO;")
        cursor.execute("select idtransaksi  FROM TRANSAKSI_HOTEL;")
        transaksi_hotel = cursor.fetchall()
        res = []
        for tup in transaksi_hotel:
            res.append((tup[0], tup[0]))
        cursor.close()

        return res
 
    
    def get_all_paket_makan():
        cursor=connection.cursor()
        cursor.execute("SET SEARCH_PATH TO SIRUCO;")
        cursor.execute("select kodepaket FROM PAKET_MAKAN;")
        paket_makan = cursor.fetchall()
        res = []
        for tup in paket_makan:
            res.append((tup[0], tup[0]))
        cursor.close()

        return res
        
    idTransaksi_Makan = forms.CharField(label='Id Transaksi Makan', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))

    idTransaksi = forms.ChoiceField(label="Id Transaksi", choices= get_data_transaksi_hotel())

class UpdateTransaksiMakanan(forms.Form):
    def get_all_paket_makan():
        cursor=connection.cursor()
        cursor.execute("SET SEARCH_PATH TO SIRUCO;")
        cursor.execute("select kodepaket FROM PAKET_MAKAN;")
        paket_makan = cursor.fetchall()
        res = []
        for tup in paket_makan:
            res.append((tup[0], tup[0]))
        cursor.close()

        return res

    idTransaksi_Makan =  forms.CharField(label='Kode Hotel', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))

    idTransaksi = forms.CharField(label='Kode Hotel', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))


    kode_hotel =  forms.CharField(label='Kode Hotel', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))

    kode_paket = forms.ChoiceField(label="Kode Paket", choices= get_all_paket_makan())

transaksi_makanan/views.py
from django.shortcuts import render

# Create your views here.
from django.http import response, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.db import connection
from .forms import CreatePaketMakanan, UpdatePaketMakanan, CreateTransaksiMakan,UpdateTransaksiMakanan
import json

def fetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return[dict(zip(columns, row)) for row in cursor.fetchall()]

def create_paket_makan(request):
    with connection.cursor() as cursor:
        response = {}
        response['error'] = False
        form = CreatePaketMakanan(request.POST or None)
        response['form'] = form
        if request.method == 'POST':
            if form.is_valid():
                kode_hotel = request.POST.get('kode_hotel')
                kode_paket = request.POST.get('kode_paket')
                nama_paket = request.POST.get('nama_paket')
                harga = request.POST.get('harga')

                    # Insert Into PAKET_MAKAN
                cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                cursor.execute("INSERT INTO PAKET_MAKAN (kodehotel,kodepaket,nama,harga) VALUES ('{}','{}','{}','{}');".format(kode_hotel,kode_paket,nama_paket,harga))

                return redirect('transaksi_makanan:list_paket_makan')

    form =  CreatePaketMakanan()

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        print(profile_data)

    args = {
        'form' : form,
        'username' : username,
        'password' : password,
        'peran' : peran
    }
    return render(request, 'create_paket_makan.html',args)

def list_paket_makan(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT KodeHotel, KodePaket, nama, harga FROM PAKET_MAKAN;')
    list_paket_makan = cursor.fetchall()
    cursor.close()

    cursor = connection.cursor()
    cursor.execute('SELECT * FROM PAKET_MAKAN WHERE kodepaket NOT IN (SELECT kodepaket FROM DAFTAR_PESAN WHERE DAFTAR_PESAN.kodehotel = PAKET_MAKAN.kodehotel AND DAFTAR_PESAN.kodepaket = PAKET_MAKAN.kodepaket);')
    belum_daftar_pesan = cursor.fetchall()

    with connection.cursor() as cursor:
        cursor.execute("SELECT kodehotel, kodepaket, nama, harga "
                            "FROM PAKET_MAKAN")
        paket_makan_data = fetchall(cursor)
        kode_hotel = paket_makan_data[0]["kodehotel"]
        kode_paket =  paket_makan_data[0]["kodepaket"]
        nama =  paket_makan_data[0]["nama"]
        harga =  paket_makan_data[0]["harga"]

        can_delete = []
        for i in paket_makan_data:
            tmp = i['kodehotel']+i['kodepaket']
            is_can = False
            for j in belum_daftar_pesan:
                tmp2 = j[0]+j[1]
                if tmp == tmp2:
                    is_can = True
            if not is_can:
                can_delete.append(0)
            else:
                can_delete.append(1)

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        print(profile_data)

        args = {
            'list_paket_makan':list(zip(list_paket_makan,can_delete)),
            'kode_hotel':kode_hotel,
            'kode_paket':kode_paket,
            'nama':nama,
            'harga':harga,
            'username' : username,
            'password' : password,
            'peran' : peran,
        }
        return render(request, 'list_paket_makan.html', args)

def update_paket_makan(request,row1, row2):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute("SELECT * FROM PAKET_MAKAN WHERE kodehotel ='{}' AND kodepaket ='{}';".format(row1,row2))
    data_paket_makan = cursor.fetchone()
    response = {}
    response['kode_hotel'] = data_paket_makan[0]
    response['kode_paket'] = data_paket_makan[1]
    response['nama_paket'] = data_paket_makan[2]
    response['harga'] = data_paket_makan[3]
    print(response)
    cursor.close()
    initial_dict = {
        'kode_hotel': response['kode_hotel'],
        'kode_paket': response['kode_paket'],
        'nama_paket': response['nama_paket'],
        'harga': response['harga'],
        }

    response['error'] = False
    form = UpdatePaketMakanan(request.POST or None, initial=initial_dict)
    response['form'] = form 

    if request.method == 'POST':
        if form.is_valid():
            kode_hotel = form.cleaned_data['kode_hotel']
            kode_paket = form.cleaned_data['kode_paket']
            nama_paket = request.POST.get('nama_paket')
            harga = request.POST.get('harga')
            
            # UPDATE PAKET MAKAN
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                cursor.execute("UPDATE PAKET_MAKAN SET kodeHotel ='{}', kodePaket ='{}', nama ='{}', harga ='{}' WHERE kodeHotel ='{}' AND kodePaket ='{}';".format(kode_hotel,kode_paket,nama_paket,harga,kode_hotel,kode_paket))
                return redirect('transaksi_makanan:list_paket_makan')

    form = UpdatePaketMakanan()
    args = {
        'form' : response['form'],
    }

    return render(request, 'update_paket_makan.html', args) 

def delete_paket_makan(request,row1,row2):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute("DELETE FROM PAKET_MAKAN WHERE kodehotel ='{}' AND kodepaket ='{}';".format(row1,row2))
    cursor.close()
    return redirect('transaksi_makanan:list_paket_makan') 

def create_transaksi_makan(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT idTransaksi FROM TRANSAKSI_HOTEL;")
        data_transaksi_hotel = list(map(lambda x:(x[0],x[0]), cursor.fetchall()))
        print(data_transaksi_hotel)

        cursor.execute("SELECT idTransaksiMakan FROM TRANSAKSI_MAKAN ORDER BY idTransaksiMakan desc LIMIT 1;")
        last_idtransaksimakan = cursor.fetchone()
        print(last_idtransaksimakan)

        id_makan = f'TRM{int(last_idtransaksimakan[0][3:]) + 1}'

    
    initialdict = {
        "idTransaksi" : data_transaksi_hotel, 
        "idTransaksi_Makan": id_makan,
        }

    response = {}
    response['error'] = False
    data = None
    if (request.method == 'POST'):
        data = json.loads(request.POST.get('data'))
    form = CreateTransaksiMakan(data or None, initial = initialdict) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            idTransaksi_Makan = form.cleaned_data['idTransaksi_Makan']
            idTransaksi =  form.cleaned_data['idTransaksi']

            #    Insert Into HOTEL
            with connection.cursor() as cursor:
                # INSERT TRANSAKSI MAKANAN
                cursor.execute("INSERT INTO TRANSAKSI_MAKAN (IdTransaksiMakan, IdTransaksi) VALUES ('{}','{}');".format(idTransaksi_Makan,idTransaksi))

                cursor.execute("SELECT id_Pesanan FROM DAFTAR_PESAN ORDER BY id_Pesanan desc LIMIT 1;")
                last_idpesanan = cursor.fetchone()[0]

                cursor.execute("SELECT KodeHotel FROM reservasi_hotel NATURAL JOIN transaksi_booking WHERE IdTransaksiBooking ='{}';".format(idTransaksi))
                kode_hotel = cursor.fetchone()[0]
                
                for kode_paket in data["listKodePaket"]:
                    # print(kode_paket)
                    cursor.execute("INSERT INTO DAFTAR_PESAN (IdTransaksiMakan, idtransaksi, id_pesanan,  KodeHotel, KodePaket ) VALUES ('{}','{}','{}','{}','{}');".format(idTransaksi_Makan,idTransaksi,last_idpesanan + 1,kode_hotel,kode_paket))
                    last_idpesanan += 1
            return JsonResponse({})

    form = CreateTransaksiMakan()

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        print(profile_data)

    args = {
        'form' : response['form'],
        'username' : username,
        'password' : password,
        'peran' : peran
    }
    return render(request, 'create_transaksi_makan.html', args)

def create_transaksi_makan2(request):
    id_makan = ''
    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM ID_KEEPER;")
        code_length = cursor.fetchone()
        print("CODE LENGTH")
        print(code_length[0])

    if code_length[0] == 0 :

        with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM TRANSAKSI_MAKAN;")
            numbase = cursor.fetchone()
            cursor.close()
            print(numbase[0])
            numbase_new = numbase[0]+1
            numbase_str = str(numbase_new)
            if numbase_new < 10:
                id_makan = 'TRM0'+ numbase_str
            else :
                id_makan = 'TRM' + numbase_str
    else :
        with connection.cursor() as cursor:
            cursor.execute("SELECT code FROM ID_KEEPER LIMIT 1;")
            numbase = cursor.fetchone()

transaksi_makanan/templates/create_paket_makan.html
{% extends 'base.html' %} 

{% block content %}

<center> Database Paket Makan </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:create_hotel' %}">Daftar hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'transaksi_makanan:create_paket_makan' %}">Daftar Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
        </ul>
    </div>
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Buat Paket Makan</center></h4></p>
        <form action="{% url 'transaksi_makanan:create_paket_makan' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">Kode Hotel</label> {{ form.kode_hotel }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kode Paket</label> {{ form.kode_paket }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Nama Paket</label> {{ form.nama_paket }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Harga</label> {{ form.harga }}
          </div>
          <input class="btn btn-primary" type="submit" value="SIMPAN">
      </form>
    </div> 
    </div>
</div>

{% endblock %}

transaksi_makanan/templates/list_paket_makan.html
{% extends "base.html" %}


{% block content %}
<style>
    .tmargin{
        padding: 32px;
    }
</style>

<center> Database Paket Makan </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>
{% if peran == "admin sistem" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:create_hotel' %}">Daftar hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_paket_makan' %}">Daftar Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
        </ul>
    </div>
</div>
{% endif %}
{% if peran == "pengpub" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_transaksi_makan' %}">Daftar Transaksi Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_transaksi_makan' %}">List Transaksi Makan</a>
            </li>
        </ul>
    </div>
</div>
{% endif %}
{% if peran == "admin satgas" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_transaksi_makan' %}">Daftar Transaksi Makan dan Daftar Pesan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_transaksi_makan' %}">List Transaksi Makan dan Daftar Pesan</a>
            </li>
        </ul>
    </div>
</div>
{% endif %}
<br>

<h2><center>List Hotel</center></h2>
<div class="tmargin table-responsive">
    <table class="table justify-content-center">
        {% if peran == "admin sistem" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Kode Paket</th>
                <th scope="col">Nama Paket</th>
                <th scope="col">Harga</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_paket_makan %}
            <tr>
                <td>{{li.0.0}}</td>
                <td>{{li.0.1}}</td>
                <td>{{li.0.2}}</td>
                <td>{{li.0.3}}</td>
                <td> 
                    <a href="{% url 'transaksi_makanan:update_paket_makan' row1=li.0 row2=li.1 %}" class="btn btn-primary btn-am bg-success update">Update</a>
                    {% if li.1 == 1 %}
                    <a href="{% url 'transaksi_makanan:delete_paket_makan' row1=li.0 row2=li.1 %}" class="btn btn-primary btn-am bg-success update">Delete</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
        {% if peran == "pengpub" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Kode Paket</th>
                <th scope="col">Nama Paket</th>
                <th scope="col">Harga</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_paket_makan %}
            <tr>
                <td>{{li.0.0}}</td>
                <td>{{li.0.1}}</td>
                <td>{{li.0.2}}</td>
                <td>{{li.0.3}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
        {% if peran == "admin satgas" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Kode Paket</th>
                <th scope="col">Nama Paket</th>
                <th scope="col">Harga</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_paket_makan %}
            <tr>
                <td>{{li.0.0}}</td>
                <td>{{li.0.1}}</td>
                <td>{{li.0.2}}</td>
                <td>{{li.0.3}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
    </table>
</div>

{% endblock %}

transaksi_makanan/templates/list_transaksi_makan.html
{% extends "base.html" %}


{% block content %}
<style>
    .tmargin{
        padding: 32px;
    }
</style>

<center> Database Transaksi Makan dan Daftar Pesan </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>
{% if peran == "pengpub" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_transaksi_makan' %}">Daftar Transaksi Makan dan Daftar Pesan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'transaksi_makanan:list_transaksi_makan' %}">List Transaksi Makan dan Daftar Pesan</a>
            </li>
        </ul>
    </div>
</div>
{% endif %}
{% if peran == "admin satgas" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_transaksi_makan' %}">Daftar Transaksi Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'transaksi_makanan:list_transaksi_makan' %}">List Transaksi Makan</a>
            </li>
        </ul>
    </div>
</div>
{% endif %}
<br>

<h2><center>List Transaksi Makan</center></h2>
<div class="tmargin table-responsive">
    <table class="table justify-content-center">
        {% if peran == "pengpub" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Id Transaksi Makan</th>
                <th scope="col">Id Transaksi</th>
                <th scope="col">Total Bayar</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_transaksi_makan %}
            <tr>
                <td>{{li.0}}</td>
                <td>{{li.1}}</td>
                <td>{{li.2}}</td>
                <td> 
                    <a href="{% url 'transaksi_makanan:detail_transaksi_makan' row1=li.0 row2=li.1 %}" class="btn btn-primary btn-am bg-success update">Detail</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
        {% if peran == "admin satgas" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Id Transaksi Makan</th>
                <th scope="col">Id Transaksi</th>
                <th scope="col">Total Bayar</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_transaksi_makan %}
            <tr>
                <td>{{li.0}}</td>
                <td>{{li.1}}</td>
                <td>{{li.2}}</td>
                <td> 
                    <a href="{% url 'transaksi_makanan:update_transaksi_makan' row1=li.0 row2=li.1 %}" class="btn btn-primary btn-am bg-success update">Update</a>
                    <a href="{% url 'transaksi_makanan:delete_transaksi_makan' row1=li.0 row2=li.1 %}" class="btn btn-primary btn-am bg-success update">Delete</a>
                    <a href="{% url 'transaksi_makanan:detail_transaksi_makan' row1=li.0 row2=li.1 %}" class="btn btn-primary btn-am bg-success update">Detail</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
    </table>
</div>

{% endblock %}