hotel/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'hotel'

urlpatterns = [
    path('hotel/create_hotel', views.form_create_hotel, name='create_hotel'),
    path('hotel/list_hotel', views.list_hotel, name='list_hotel'),
    path('hotel/update_hotel/<str:row>', views.form_update_hotel, name='update_hotel'),
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
]

siruco/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('user_profile.urls')),
    path('', include('rumahsakit.urls')),
    path('', include('faskes.urls')),
    path('',include('pasien.urls')),
    path('',include('hotel.urls')),
    path('',include('transaksi_makanan.urls')), 
    path('', include('transaksi_rs.urls'))
]

transaksi_makanan/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'transaksi_makanan'

urlpatterns = [
    path('transaksi_makan/create_paket_makan', views.create_paket_makan, name='create_paket_makan'),
    path('transaksi_makan/list_paket_makan', views.list_paket_makan, name='list_paket_makan'),
    path('transaksi_makan/update_paket_makan/<str:row1>/<str:row2>', views.update_paket_makan, name='update_paket_makan'),
    path('transaksi_makan/delete_paket_makan/<str:row1>/<str:row2>', views.delete_paket_makan, name='delete_paket_makan'),
    path('transaksi_makan/create_transaksi_makan', views.create_transaksi_makan, name='create_transaksi_makan'),
    path('transaksi_makan/list_transaksi_makan', views.list_transaksi_makan, name='list_transaksi_makan'),
    path('transaksi_makan/delete_transaksi_makan/<str:row1>/<str:row2>', views.delete_transaksi_makan, name='delete_transaksi_makan'),
    path('transaksi_makan/update_transaksi_makan/<str:row1>/<str:row2>', views.update_transaksi_makan, name='update_transaksi_makan'),
    path('transaksi_makan/detail_transaksi_makan/<str:row1>/<str:row2>', views.detail_transaksi_makan, name='detail_transaksi_makan'),
    path('transaksi_makan/get_kode_hotel', views.get_kode_hotel, name='get_kode_hotel'),
]

hotel/models.py
from django.db import models

# Create your models here.

hotel/forms.py
from django import forms
from django.db import connection

class CreateHotel(forms.Form):
    kode_hotel = forms.CharField(label='Kode Hotel', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))

    #nama hotel : isian
    nama_hotel = forms.CharField(label='Nama Hotel', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama hotel',
        'type' : 'text',
        'required': True,
    }))

    #Rujukan: ☑ [Checkbox bisa diklik]
    rujukan = forms.BooleanField(label='rujukan', required=False)

    #Alamat:
    # Jalan: [Isian]
    jalan = forms.CharField(label='Jalan', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama jalan',
        'type' : 'text',
        'required': True,
    }))
    #  Kelurahan: [Isian]
    kelurahan = forms.CharField(label='Kelurahan', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama kelurahan',
        'type' : 'text',
        'required': True,
    }))
    #  Kecamatan: [Isian]
    kecamatan = forms.CharField(label='kecamatan', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama kecamatan',
        'type' : 'text',
        'required': True,
    }))
    #  Kabupaten/Kota: [Isian]
    kabkot = forms.CharField(label='Kabupaten/Kota', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama kabupaten atau kota',
        'type' : 'text',
        'required': True,
    }))
    #  Provinsi: [Isian]
    provinsi = forms.CharField(label='Provinsi', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama provinsi',
        'type' : 'text',
        'required': True,
    }))

class UpdateHotel(forms.Form):
    kode_hotel = forms.CharField(label='Kode Hotel', max_length=10, disabled = True, widget = forms.TextInput(attrs={
        'readonly':'readonly'
    }))

    nama_hotel = forms.CharField(label='Nama Hotel', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama hotel',
        'type' : 'text',
        'required': True,
    }))

    #Rujukan: ☑ [Checkbox bisa diklik]
    rujukan = forms.BooleanField(label='rujukan',required=False)

    #Alamat:
    # Jalan: [Isian]
    jalan = forms.CharField(label='Jalan', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama jalan',
        'type' : 'text',
        'required': True,
    }))
    #  Kelurahan: [Isian]
    kelurahan = forms.CharField(label='Kelurahan', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama kelurahan',
        'type' : 'text',
        'required': True,
    }))
    #  Kecamatan: [Isian]
    kecamatan = forms.CharField(label='kecamatan', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama kecamatan',
        'type' : 'text',
        'required': True,
    }))
    #  Kabupaten/Kota: [Isian]
    kabkot = forms.CharField(label='Kabupaten/Kota', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama kabupaten atau kota',
        'type' : 'text',
        'required': True,
    }))
    #  Provinsi: [Isian]
    provinsi = forms.CharField(label='Provinsi', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis nama provinsi',
        'type' : 'text',
        'required': True,
    }))

hotel/views.py
from django.shortcuts import render

# Create your views here.
from django.http import response
from django.shortcuts import render, redirect
from django.db import connection
from .forms import CreateHotel, UpdateHotel

def fetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return[dict(zip(columns, row)) for row in cursor.fetchall()]


def form_create_hotel(request):
    kode_hotel = ''
    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM HOTEL;")
        numbase = cursor.fetchone()
        cursor.close()
        print(numbase[0])
        numbase_new = numbase[0]+1
        numbase_str = str(numbase_new)
        if numbase_new < 10:
            kode_hotel = 'H0'+ numbase_str
        else :
            kode_hotel = 'H' + numbase_str

    initialdict = {"kode_hotel" : kode_hotel}
    response = {}
    form = CreateHotel(request.POST or None, initial= initialdict) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            print("form valid")
            kode_hotel = form.cleaned_data['kode_hotel']
            nama_hotel = request.POST.get('nama_hotel')
            rujukan = form.cleaned_data['rujukan']
            if rujukan == True :
                rujukan = 1
            if rujukan == False :
                rujukan =  0
            jalan = request.POST.get('jalan')
            kelurahan = request.POST.get('kelurahan')
            kecamatan = request.POST.get('kecamatan')
            kabkot = request.POST.get('kabkot')
            provinsi = request.POST.get('provinsi')

            #    Insert Into HOTEL
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                cursor.execute("INSERT INTO HOTEL (Kode, nama, isRujukan, jalan, kelurahan, kecamatan, kabkot, prov) VALUES ('{}','{}','{}','{}','{}','{}','{}','{}');".format(kode_hotel,nama_hotel,rujukan,jalan,kelurahan,kecamatan,kabkot,provinsi))
                print("anjinggg")
                return redirect('hotel:list_hotel')
    
    form = CreateHotel()

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        print(profile_data)

    args = {
        'form' : response['form'],
        'username' : username,
        'password' : password,
        'peran' : peran
    }
    return render(request, 'create_hotel.html', args)
    
def list_hotel(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT kode, nama, isRujukan, jalan, kelurahan, kecamatan, kabkot, prov FROM HOTEL ORDER BY KODE;')
    list_hotel = cursor.fetchall()
    print(list_hotel)
    print(len(list_hotel))

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        print(profile_data)

    args = {
        'list_hotel':list_hotel,
        'username' : username,
        'password' : password,
        'peran' : peran,
        }
    return render(request, 'list_hotel.html', args)

def form_update_hotel(request,row):
    print(row)
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT * FROM HOTEL WHERE kode = %s;',[row])
    data_hotel = cursor.fetchone()
    response = {}
    response['kode'] = data_hotel[0]
    response['nama'] = data_hotel[1]
    response['isRujukan'] = data_hotel[2]
    response['jalan'] = data_hotel[3]
    response['kelurahan'] = data_hotel[4]
    response['kecamatan'] = data_hotel[5]
    response['kabkot'] = data_hotel[6]
    response['prov'] = data_hotel[7]
    print(response)
    cursor.close()
    initial_dict = {
        "kode_hotel":response['kode'], 
        "nama_hotel":response['nama'], 
        "isRujukan":response['isRujukan'], 
        "jalan":response['jalan'], 
        "kelurahan":response['kelurahan'],
        "kecamatan":response['kecamatan'],
        "kabkot":response['kabkot'], 
        "provinsi":response['prov']
        }

    response['error'] = False
    form = UpdateHotel(request.POST or None, initial=initial_dict)
    response['form'] = form 

    if request.method == 'POST':
        if form.is_valid():
            kode_hotel = form.cleaned_data['kode_hotel']
            nama_hotel = request.POST.get('nama_hotel')
            rujukan = form.cleaned_data['rujukan']
            if rujukan == True :
                rujukan = 1
            if rujukan == False :
                rujukan =  0
            jalan = request.POST.get('jalan')
            kelurahan = request.POST.get('kelurahan')
            kecamatan = request.POST.get('kecamatan')
            kabkot = request.POST.get('kabkot')
            provinsi = request.POST.get('provinsi')

            # UPDATE HOTEL
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                cursor.execute("UPDATE HOTEL SET kode ='{}', nama ='{}', isRujukan ='{}', jalan ='{}', kelurahan ='{}', kecamatan ='{}', kabkot ='{}', prov ='{}' WHERE kode ='{}';".format(kode_hotel,nama_hotel,rujukan,jalan,kelurahan,kecamatan,kabkot,provinsi,kode_hotel))
                return redirect('hotel:list_hotel')

    form = UpdateHotel()
    args = {
        'form' : response['form'],
    }

    return render(request, 'update_hotel.html', args) 

hotel/templates/create_hotel.html
{% extends 'base.html' %} 

{% block content %}

<center> Database Hotel </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'hotel:create_hotel' %}">Daftar hotel</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'transaksi_makanan:create_paket_makan' %}">Daftar Paket Makan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
        </li>
      </ul>
    </div>
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Buat Hotel</center></h4></p>
        <form action="{% url 'hotel:create_hotel' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">Kode Hotel</label> {{ form.kode_hotel }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Nama Hotel</label> {{ form.nama_hotel }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Rujukan</label> {{ form.rujukan }}
          </div>
          <h3>Alamat :</h3>
          <br>
          <div class="form-group">
            <label for="validationDefault01">Jalan</label> {{ form.jalan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kelurahan</label> {{ form.kelurahan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kecamatan</label> {{ form.kecamatan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kabupaten/Kota</label> {{ form.kabkot }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Provinsi</label> {{ form.provinsi }}
          </div>
          <input class="btn btn-primary" type="submit" value="SIMPAN">
      </form>
    </div> 
    </div>
</div>

{% endblock %}

hotel/templates/list_hotel.html
{% extends "base.html" %}


{% block content %}
<style>
    .tmargin{
        padding: 32px;
    }
</style>

<center> Database Hotel </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>
{% if peran == "admin sistem" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hotel:create_hotel' %}">Daftar hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_paket_makan' %}">Daftar Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
          </ul>
    </div>
</div>
{% endif %}
{% if peran == "pengpub" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_transaksi_makan' %}">Daftar Transaksi Makan dan Daftar Pesan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_transaksi_makan' %}">List Transaksi Makan dan Daftar Pesan</a>
            </li>
          </ul>
    </div>
</div>
{% endif %}
{% if peran == "admin satgas" %}
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'hotel:list_hotel' %}">List Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_paket_makan' %}">List Paket Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:create_transaksi_makan' %}">Daftar Transaksi Makan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transaksi_makanan:list_transaksi_makan' %}">List Transaksi Makan</a>
            </li>
          </ul>
    </div>
</div>
{% endif %}
<br>

<h2><center>List Hotel</center></h2>
<div class="tmargin table-responsive">
    <table class="table justify-content-center">
        {% if peran == "admin sistem" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Nama Hotel</th>
                <th scope="col">Status Rujukan</th>
                <th scope="col">Alamat</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_hotel %}
            <tr>
                <td>{{li.0}}</td>
                <td>{{li.1}}</td>
                {% if li.2 == '1' %}
                <td><input disabled type="checkbox" checked></td>
                {% endif %}
                {% if li.2 == '0' %}
                <td><input disabled type="checkbox"></td>
                {% endif %}
                <td>{{li.3}},{{li.4}},{{li.5}},{{li.6}},{{li.7}}</td>
            
                <td> 
                    <a href="{% url 'hotel:update_hotel' row=li.0 %}" class="btn btn-primary btn-am bg-success update">Update</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
        {% if peran == "pengpub" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Nama Hotel</th>
                <th scope="col">Status Rujukan</th>
                <th scope="col">Alamat</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_hotel %}
            <tr>
                <td>{{li.0}}</td>
                <td>{{li.1}}</td>
                {% if li.2 == '1' %}
                <td><input disabled type="checkbox" checked></td>
                {% endif %}
                {% if li.2 == '0' %}
                <td><input disabled type="checkbox"></td>
                {% endif %}
                <td>{{li.3}},{{li.4}},{{li.5}},{{li.6}},{{li.7}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
        {% if peran == "admin satgas" %}
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Nama Hotel</th>
                <th scope="col">Status Rujukan</th>
                <th scope="col">Alamat</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_hotel %}
            <tr>
                <td>{{li.0}}</td>
                <td>{{li.1}}</td>
                {% if li.2 == '1' %}
                <td><input disabled type="checkbox" checked></td>
                {% endif %}
                {% if li.2 == '0' %}
                <td><input disabled type="checkbox"></td>
                {% endif %}
                <td>{{li.3}},{{li.4}},{{li.5}},{{li.6}},{{li.7}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
    </table>
</div>

{% endblock %}

hotel/templates/update_hotel.html
{% extends 'base.html' %} 
{% block content %}

<center> Database Hotel </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
   
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Update Data Hotel</center></h4></p>
     
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">Kode Hotel</label> {{ form.kode_hotel }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Nama Hotel</label> {{ form.nama_hotel }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Rujukan</label> {{ form.rujukan }}
          </div>
          <h3>Alamat :</h3>
          <br>
          <div class="form-group">
            <label for="validationDefault01">Jalan</label> {{ form.jalan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kelurahan</label> {{ form.kelurahan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kecamatan</label> {{ form.kecamatan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kabupaten/Kota</label> {{ form.kabkot }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Provinsi</label> {{ form.provinsi }}
          </div>
          <input class="btn btn-primary" type="submit" value="UPDATE">
      </form>
    </div> 
    </div>
</div>

{% endblock %}