faskes/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'faskes'

urlpatterns = [
    # path('rumahsakit/', views.create_rs, name='create_rs'),
    path('faskes/create_faskes', views.form_create_faskes, name='create_form_faskes'),
    path('faskes/list_faskes', views.list_faskes, name='list_faskes'),
    path('faskes/detail_faskes/<str:row>', views.detail_faskes, name='detail_faskes'),
    path('faskes/update_faskes/<str:row>/', views.form_update_faskes, name='update_faskes'),
    path('faskes/delete_faskes/<str:row>', views.delete_faskes, name='delete_faskes'),
    path('faskes/create_jadwal', views.form_create_jadwal, name='create_form_jadwal'),
    path('faskes/list_jadwal', views.list_jadwal, name='list_jadwal')
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
]

siruco/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('user_profile.urls')),
    path('', include('rumahsakit.urls')),
    path('', include('faskes.urls')),
    path('',include('pasien.urls')),
    path('',include('hotel.urls')),
    path('',include('transaksi_makanan.urls')), 
    path('', include('transaksi_rs.urls'))
]

faskes/models.py
from django.db import models

# Create your models here.

faskes/views.py
from django.http import response
from django.shortcuts import render, redirect
from django.db import connection
from .forms import CreateFaskes, UpdateFaskes,CreateJadwal

# Create your views here.

def fetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return[dict(zip(columns, row)) for row in cursor.fetchall()]
    
def list_faskes(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT kode, nama, tipe FROM FASKES;')
    list_faskes = cursor.fetchall()
    print(list_faskes)
    print(len(list_faskes))

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        cursor.execute("SELECT idfaskes FROM ADMIN_SATGAS WHERE username = '{}';".format(email))
        akun_data = fetchall(cursor)
        print(profile_data)
        print(akun_data)
        print(akun_data[0]['idfaskes'])
        id_faskes = akun_data[0]['idfaskes']
        print(id_faskes)

    args = {'list_faskes':list_faskes,
            'username' : username,
            'password' : password,
            'peran' : peran,
            'id_faskes' : id_faskes}
    return render(request, 'list_faskes.html', args)

def detail_faskes(request, row):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT * FROM FASKES WHERE kode = %s;',[row])
    data_faskes = cursor.fetchone()
    response = {}
    response['kode'] = data_faskes[0]
    response['tipe'] = data_faskes[1]
    response['nama'] = data_faskes[2]
    response['status_kepemilikan'] = data_faskes[3]
    response['jalan'] = data_faskes[4]
    response['kelurahan'] = data_faskes[5]
    response['kecamatan'] = data_faskes[6]
    response['kabkot'] = data_faskes[7]
    response['provinsi'] = data_faskes[8]
    print(response)
    cursor.close()

    return render(request, 'detail_faskes.html', response)

def form_create_faskes(request):
    code = ''
    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM CODE_KEEPER;")
        code_length = cursor.fetchone()
        print("CODE LENGTH")
        print(code_length[0])

    if code_length[0] == 0 :

        with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM FASKES;")
            numbase = cursor.fetchone()
            cursor.close()
            print(numbase[0])
            numbase_new = numbase[0]+1
            numbase_str = str(numbase_new)
            if numbase_new < 10:
                code = 'F0'+ numbase_str
            else :
                code = 'F' + numbase_str

    else :

        with connection.cursor() as cursor:
            cursor.execute("SELECT code FROM CODE_KEEPER LIMIT 1;")
            numbase = cursor.fetchone()
            print(numbase[0])
            code = numbase[0]


    initialdict = {"kode" : code}

    print(initialdict)
    response = {}
    response['error'] = False
    form = CreateFaskes(request.POST or None, initial = initialdict) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            kode_faskes = form.cleaned_data['kode']
            tipe = request.POST.get('tipe')
            nama_faskes = request.POST.get('nama_faskes')
            status_kepemilikan = request.POST.get('status_kepemilikan')
            jalan = request.POST.get('jalan')
            kelurahan = request.POST.get('kelurahan')
            kecamatan = request.POST.get('kecamatan')
            kabkot = request.POST.get('kabkot')
            provinsi = request.POST.get('provinsi')

            #    Insert Into FASKES
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                cursor.execute("INSERT INTO FASKES VALUES ('{}','{}','{}','{}','{}','{}','{}','{}','{}');".format(kode_faskes,tipe,nama_faskes,status_kepemilikan,jalan,kelurahan,kecamatan,kabkot,provinsi))
                print('test')

                cursor.execute("SELECT COUNT(*) FROM CODE_KEEPER;")
                code_length = cursor.fetchone()
                print("CODE LENGTH")
                print(code_length[0])

                if code_length != 0:
                    cursor.execute("DELETE FROM CODE_KEEPER WHERE code = '{}';".format(code))


                return redirect('faskes:list_faskes') 

    form = CreateFaskes()

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        print(profile_data)

    args = {
        'form' : response['form'],
        'username' : username,
        'password' : password,
        'peran' : peran
    }
    return render(request, 'create_faskes.html', args)

def form_update_faskes(request, row):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT * FROM FASKES WHERE kode = %s;',[row])
    data_faskes = cursor.fetchone()
    response = {}
    response['kode'] = data_faskes[0]
    response['tipe'] = data_faskes[1]
    response['nama'] = data_faskes[2]
    response['status_kepemilikan'] = data_faskes[3]
    response['jalan'] = data_faskes[4]
    response['kelurahan'] = data_faskes[5]
    response['kecamatan'] = data_faskes[6]
    response['kabkot'] = data_faskes[7]
    response['provinsi'] = data_faskes[8]
    print(response)
    cursor.close()
    initial_dict = {"kode":response['kode'], "tipe":response['tipe'], "nama_faskes":response['nama'], "status_kepemilikan":response['status_kepemilikan'], "jalan":response['jalan'], "kelurahan":response['kelurahan'],"kecamatan":response['kecamatan'],"kabkot":response['kabkot'], "provinsi":response['provinsi']}

    response['error'] = False
    form = UpdateFaskes(request.POST or None, initial=initial_dict) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            kode_faskes = form.cleaned_data['kode']
            tipe = request.POST.get('tipe')
            nama_faskes = request.POST.get('nama_faskes')
            status_kepemilikan = request.POST.get('status_kepemilikan')
            jalan = request.POST.get('jalan')
            kelurahan = request.POST.get('kelurahan')
            kecamatan = request.POST.get('kecamatan')
            kabkot = request.POST.get('kabkot')
            provinsi = request.POST.get('provinsi')

            # UPDATE FASKES
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                cursor.execute("UPDATE FASKES SET kode ='{}', tipe = '{}', nama = '{}', statusmilik = '{}', jalan = '{}', kelurahan = '{}', kecamatan = '{}', kabkot = '{}', prov = '{}' WHERE kode = '{}';".format(kode_faskes,tipe,nama_faskes,status_kepemilikan,jalan,kelurahan,kecamatan,kabkot,provinsi,kode_faskes))
                print('test')
                return redirect('faskes:list_faskes') 
    
    form = UpdateFaskes()
    args = {
        'form' : response['form'],
    } 

    return render(request, 'update_faskes.html', args)

def delete_faskes(request,row):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute("INSERT INTO CODE_KEEPER VALUES('{}');".format(row))
    cursor.execute('DELETE FROM FASKES WHERE kode = %s;',[row])
    cursor.close()
    
    return redirect('faskes:list_faskes') 

def form_create_jadwal(request):
    response = {}
    response['error'] = False
    form = CreateJadwal(request.POST or None) 
    response['form'] = form
    if request.method == 'POST':
        if form.is_valid():
            kode = request.POST.get('kode')
            shift = request.POST.get('shift')
            tanggal = request.POST.get('tanggal')

            #    Insert Into JADWAL
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIRUCO;")
                cursor.execute("INSERT INTO JADWAL VALUES ('{}','{}','{}');".format(kode,shift,tanggal))
                print('test_jadwal')
                return redirect('faskes:list_jadwal') 

    form = CreateJadwal()

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]
        password = profile_data[0]["password"]
        peran = profile_data[0]["peran"]
        print(profile_data)

    args = {
        'form' : response['form'],
        'username' : username,
        'password' : password,
        'peran' : peran
    }
    return render(request, 'create_jadwal.html', args)

def list_jadwal(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT kode_faskes, shift, tanggal FROM JADWAL;')
    list_jadwal = cursor.fetchall()
    print(list_jadwal)
    print(len(list_jadwal))

    email = request.session.get("username_account")
    print(email)
    with connection.cursor() as cursor:
        cursor.execute("SELECT username, password, peran "
                        "FROM AKUN_PENGGUNA WHERE username = '{}'".format(email))
        profile_data = fetchall(cursor)
        username = profile_data[0]["username"]

faskes/templates/create_faskes.html
{% extends 'base.html' %} 
{% block content %}

<center> Database Faskes </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          {% if peran == "admin satgas" %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'faskes:create_form_faskes' %}">Buat Faskes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'faskes:list_faskes' %}">List Faskes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'faskes:create_form_jadwal' %}">Buat Jadwal Faskes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faskes:list_jadwal' %}">List Jadwal Faskes</a>
        </li>
        {% endif %}
        </ul>
    </div>
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Create Fasilitas Kesehatan</center></h4></p>
     
        <form action="{% url 'faskes:create_form_faskes' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">Kode Faskes</label> {{ form.kode }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Tipe</label> {{ form.tipe }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Nama Faskes</label> {{ form.nama_faskes }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Status Kepemilikan</label> {{ form.status_kepemilikan }}
          </div>
          <h3>Alamat :</h3>
          <br>
          <div class="form-group">
            <label for="validationDefault01">Jalan</label> {{ form.jalan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kelurahan</label> {{ form.kelurahan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kecamatan</label> {{ form.kecamatan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kabupaten/Kota</label> {{ form.kabkot }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Provinsi</label> {{ form.provinsi }}
          </div>
          <input class="btn btn-primary" type="submit" value="SIMPAN">
      </form>
    </div> 
    </div>
{% endblock %}

faskes/templates/create_jadwal.html
{% extends 'base.html' %} 
{% block content %}

<center> Database Faskes </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          {% if peran == "admin satgas" %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'faskes:create_form_faskes' %}">Buat Faskes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'faskes:list_faskes' %}">List Faskes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'faskes:create_form_jadwal' %}">Buat Jadwal Faskes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faskes:list_jadwal' %}">List Jadwal Faskes</a>
        </li>
        {% endif %}
        </ul>
    </div>
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Create Fasilitas Kesehatan</center></h4></p>
     
        <form action="{% url 'faskes:create_form_jadwal' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">Faskes</label> {{ form.kode }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Shift</label> {{ form.shift }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Tanggal</label> {{ form.tanggal }}
          </div>
          <input class="btn btn-primary" type="submit" value="SIMPAN">
      </form>
    </div> 
    </div>
{% endblock %}

faskes/templates/detail_faskes.html
{% extends 'base.html' %} 
{% block content %}

<div class="container px-4 px-lg-5 mt-5">
    <div class="card">
        <h5>Kode Faskes: {{kode}}</h5>
        <h5>Tipe: {{tipe}}</h5>
        <h5>Nama Faskes: {{nama}}</h5>
        <h5>Status: {{status_kepemilikan}}</h5>
        <br>
        <h5>Alamat:</h5>
        <h5>Jalan: {{jalan}}</h5>
        <h5>Kelurahan: {{kelurahan}}</h5>
        <h5>Kecamatan: {{kecamatan}}</h5>
        <h5>Kabupaten/Kota: {{kabkot}}</h5>
        <h5>Provinsi: {{provinsi}}</h5>
    </div>
</div>

{% endblock %}

faskes/templates/list_faskes.html
{% extends "base.html" %}


{% block content %}
<style>
    .tmargin{
        padding: 32px;
    }
</style>

<center> Database Faskes </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link " href="{% url 'faskes:create_form_faskes' %}">Buat Faskes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'faskes:list_faskes' %}">List Faskes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'faskes:create_form_jadwal' %}">Buat Jadwal Faskes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'faskes:list_jadwal' %}">List Jadwal Faskes</a>
          </li>
        </ul>
    </div>
<br>

<h2><center>List Fasilitas Kesehatan</center></h2>
<div class="tmargin table-responsive">
    <table class="table justify-content-center">
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Kode Faskes</th>
                <th scope="col">Tipe</th>
                <th scope="col">Nama Faskes</th>
                <th scope="col">Action</th>
                <!-- {% if request.session.role == "ADMIN_APOTEK" %}
                <th scope="col">Action [ADMIN]</th>
                {% endif %} -->
            </tr>
        </thead>
        <tbody>
          {% for li in list_faskes %}
            <tr>
                <td>{{li.0}}</td>
                <td>{{li.2}}</td>
                <td>{{li.1}}</td>
                <td> 
                    {%if li.0 == id_faskes %}
                    <a class="btn btn-primary btn-am bg-success update" href="{% url 'faskes:update_faskes' row=li.0 %}">Update</a>
                    <a class="btn btn-primary btn-am bg-success update disabled" href="{% url 'faskes:delete_faskes' row=li.0 %}">Delete</a>
                    <a class="btn btn-primary btn-am bg-success update" href="{% url 'faskes:detail_faskes' row=li.0 %}">Detail</a>
                    {% else %}
                    <a class="btn btn-primary btn-am bg-success update" href="{% url 'faskes:update_faskes' row=li.0 %}">Update</a>
                    <a class="btn btn-primary btn-am bg-success update" href="{% url 'faskes:delete_faskes' row=li.0 %}">Delete</a>
                    <a class="btn btn-primary btn-am bg-success update" href="{% url 'faskes:detail_faskes' row=li.0 %}">Detail</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

faskes/templates/list_jadwal.html
{% extends "base.html" %}


{% block content %}
<style>
    .tmargin{
        padding: 32px;
    }
</style>

<center> Database Faskes </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link " href="{% url 'faskes:create_form_faskes' %}">Buat Faskes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'faskes:list_faskes' %}">List Faskes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'faskes:create_form_jadwal' %}">Buat Jadwal Faskes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'faskes:list_jadwal' %}">List Jadwal Faskes</a>
          </li>
        </ul>
    </div>
<br>

<h2><center>List jadwal Fasilitas Kesehatan</center></h2>
<div class="tmargin table-responsive">
    <table class="table justify-content-center">
        <thead class="bg-danger text-white align-items-center">
            <tr>
                <th scope="col">Nomor</th>
                <th scope="col">Faskes</th>
                <th scope="col">Shift</th>
                <th scope="col">Tanggal</th>
            </tr>
        </thead>
        <tbody>
          {% for li in list_jadwal %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{li.0}}</td>
                <td>{{li.1}}</td>
                <td>{{li.2}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

faskes/templates/update_faskes.html
{% extends 'base.html' %} 
{% block content %}

<center> Database Faskes </center>
</h1>
<h5>
    <center> Pilih opsi yang ingin anda lakukan </center>
</h5>

<div class="card">
   
    <div class="card-body form_bg_color "></div>
    <div class="outer-form container form-column col-md-4 ">
        <p class="tulisan_login"><h4><center>Form Update Fasilitas Kesehatan</center></h4></p>
     
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault01">Kode Faskes</label> {{ form.kode }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Tipe</label> {{ form.tipe }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Nama Faskes</label> {{ form.nama_faskes }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Status Kepemilikan</label> {{ form.status_kepemilikan }}
          </div>
          <h3>Alamat :</h3>
          <br>
          <div class="form-group">
            <label for="validationDefault01">Jalan</label> {{ form.jalan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kelurahan</label> {{ form.kelurahan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kecamatan</label> {{ form.kecamatan }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Kabupaten/Kota</label> {{ form.kabkot }}
          </div>
          <div class="form-group">
            <label for="validationDefault01">Provinsi</label> {{ form.provinsi }}
          </div>
          <input class="btn btn-primary" type="submit" value="UPDATE">
      </form>
    </div> 
    </div>
</div>

{% endblock %}